## GitHub Actions ##
name: SonarCloud Scan

#
# Documentation:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - "master"
      - "feature*"  
###############################
# Set The Job
# runs-on: ubuntu-latest
##############################

jobs:
  SonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Analyse with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
